from django.contrib.auth.models import User # get_user_model  User = get_user_model()
User.objects.create_superuser('admin', 'billyrusslee@gmail.com', '111')
print('\n\nADMIN created\n\n')
User.objects.create_superuser('admin2', 'billyrusslee@gmail.com', '111')
print('\n\nADMIN2 created\n\n')
User.objects.create_superuser('admin3', 'billyrusslee@gmail.com', '111')
print('\n\nADMIN3 created\n\n')
