# Generated by Django 3.0.3 on 2020-02-27 18:54

from django.db import migrations, models
import django.db.models.deletion
import sn_mixins.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_name', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('deleted', models.BooleanField(default=False)),
                ('chat_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_chats', to='accounts.Profile')),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.CreateModel(
            name='ChatUnion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=sn_mixins.functions.upload_location, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('readed', models.BooleanField(default=False)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner_msgs', to='chats.Chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_msgs', to='accounts.Profile')),
            ],
            options={
                'ordering': ['-created', '-updated'],
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='chat_union',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relative_chats', to='chats.ChatUnion'),
        ),
    ]
