"""
Django settings for SN project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECRET_KEY = 'dx3bk!#mi*93%(ojabhulj#%#fkv=bao6g+v)trk72sx3!6ff6'



# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

SECRET_KEY = 'dummy-secret' if DEBUG else env('DJANGO_SECRET_KEY')

dhcp_ip_list = [f'192.168.0.{i}' for i in range(3,101)]
localhost_ips = ['0.0.0.0', '127.0.0.1']
dhcp_ip_list.extend(localhost_ips)


ALLOWED_HOSTS = dhcp_ip_list if DEBUG else ['social_network.com']


# Application definition


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'sn_mixins',

    'posts',
    'likes',
    'comments',

    'chats',
    
    'accounts',

    'password_reset',

    'rest_framework',
    'psycopg2',
    'crispy_forms',
    'markdown_deux',
    'pagedown',

    # 'django_extensions',
]

CRISPY_TEMPLATE_PACK = 'bootstrap3'


# SMTP server, change to SMTP of your mailbox
EMAIL_HOST = 'smtp.gmail.com' # smtp.gmail.com
# mailbox name
EMAIL_HOST_USER = 'max.ulshin.1997@gmail.com'
# Mailbox password
EMAIL_HOST_PASSWORD = 'cFdnewSdn32D12iodF'
# Port for sending mail
EMAIL_PORT = 587
# Whether to use TLS or not
EMAIL_USE_TLS = True
# Default sender
DEFAULT_FROM_EMAIL = 'My personal Chat website'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SN.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SN.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'social_network',
        'USER': 'postgres',
        'PASSWORD': '111',
        'HOST': '',
        'PORT': '5432',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "static_files")

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media_sn")

SILENCED_SYSTEM_CHECKS = [
    'admin.E408',
    'admin.E409',
    'admin.E410',
]

LOGIN_URL = 'accounts/login'

# list_all_hosts = [f'192.168.0.{i}' for i in range(3,101)].extend(['0.0.0.0', '127.0.0.1'])
# ALLOWED_HOSTS = [f'192.168.0.{i}' for i in range(3,101)].extend(['0.0.0.0', '127.0.0.1'])# ['0.0.0.0', '127.0.0.1', '192.168.0.0'] #
